### ISSUE TITLE
Block callback

### ISSUE THREAD

**Issue by purepure** [soomla/ios-store#36]
Firstly, your library is very cool and help developer so much.
I would like to prefer this project block callback method so developer can handle callback easier and handy. 
Btw, handle non-comsumer is highly recommend.

Thank so much

**Comment by gurdotan** [comment]
Hi,

Can you provide a link to the code lines you're referring to? Which file and where?
We do handle non consumable items if that's what you meant.  You can use them with a `LifetimeVG` that uses `PurchaseWithMarket`

**Comment by purepure** [comment]
callback function like that:
[[RMStore defaultStore] addPayment:productID success:^(SKPaymentTransaction *transaction) {
    NSLog(@"Purchased!");
} failure:^(SKPaymentTransaction *transaction, NSError *error) {
    NSLog(@"Something went wrong");
}];

It is RMStore: https://github.com/robotmedia/RMStore

Thank

**Comment by gurdotan** [comment]
You can register handlers to our notifications which achieves the same effect.  Have a look at this example:
https://github.com/soomla/ios-store/blob/75a10d8f425c1e6a48d1f09410ac86ed69c38f18/SoomlaiOSStoreExample/SoomlaiOSStoreExample/VirtualCurrencyPacksViewController.m#L48

You can also see our full list of events here:
https://github.com/soomla/ios-store/blob/75a10d8f425c1e6a48d1f09410ac86ed69c38f18/SoomlaiOSStore/StoreEventHandling.h

**Comment by refaelos** [comment]
Closing this issue. Open if needed.
