### ISSUE TITLE
Getting the receipt NSData as base64 encode string after market purchase

### ISSUE THREAD

**Issue by nikolajpedersen** [soomla/ios-store#37]
We would like to access the receipt when a purchase is done.

Right now you get a "receipt" field with the file URL of the receipt, but we need the contents (NSData) base64 encoded. Perhaps returning an extra field "receipt_data" with this?

Is this something (the proposed added field) you would accept as a pull request and potentially merge?
If not - how could we code this in another way that you would accept?

**Comment by refaelos** [comment]
Yup. We got this request in http://answers.soom.la

We'll be happy to merge a pull-request of something like this. If you want to implement it and need assistance let me know.
