### ISSUE TITLE
Fetch item information from store

### ISSUE THREAD

**Issue by purepure** [soomla/ios-store#40]
Your lib is very handy and power but I am wondering how can I fetch information of a item (and entire item list) from store?. I need this function because of sometime we want to discount or update price without re-submit new client.

**Comment by refaelos** [comment]
yes. it's possible. Call 'refreshMarketItemsDetails'
https://github.com/soomla/ios-store/blob/master/SoomlaiOSStore/SoomlaStore.h#L85

The refreshed data will automatically be in the relevant [MarketItem](https://github.com/soomla/ios-store/blob/master/SoomlaiOSStore/domain/MarketItem.h#L39) in the fields that start with "market..."
