### ISSUE TITLE
Revisiting Verification handling - possible error 

### ISSUE THREAD

**Issue by zentuit** [soomla/ios-store#42]
Hey folks,
Sorry I've been incommunicado for a bit; I've had some family and time pressures keeping me very busy.

While working on improving verifications some more (which I'll open in another issue:https://github.com/soomla/ios-store/issues/43 ) I saw what is a possible error in commit https://github.com/soomla/ios-store/commit/4ab983e3048d3585d25302880a78f7e6bd85b8d4. The following was added to *SoomlaiOSStore/SoomlaVerification.m*:
```
     BOOL verified = NO;
     if (responseCode==200 && verifiedNum) {
+        
         verified = [verifiedNum boolValue];
+        if (!verified) {
+            NSNumber* emptyResponse = (NSNumber*)[responseDict objectForKey:@"emptyResponse"];
+            BOOL needRefresh = [emptyResponse boolValue];
+            if (needRefresh && tryAgain) {
+                LogDebug(TAG, @"Receipt refresh needed.");
+                tryAgain = NO;
+                SKReceiptRefreshRequest *req = [[SKReceiptRefreshRequest alloc] initWithReceiptProperties:nil];
+                req.delegate = self;
+                [req start];
+                
+                // we return here ...
+                return;
+            }
+        }
```
unless I'm missing something, that large block starting at `if (!verified) {` will not ever fire. The previous if statement has `&& verifiedNum` as a condition. If that is false, then the if block won't be entered. Which means only if *verifiedNum* is true will the if block pass, in which case `if (!verified) {` will never pass. Am I correct in my analysis?

**Comment by refaelos** [comment]
Not sure you're correct on this. See this code:
```
    NSNumber* n = [NSNumber numberWithInt:0];
    if (n) {
        NSLog(@"It's true");
    }
```

This will print `It's true`.
The condition will only be false if it's null.

**Comment by zentuit** [comment]
I missed that verifiedNum is NSNumber* and not an int.  Ooops.
