### ISSUE TITLE
Proposal for improvements in Verifications

### ISSUE THREAD

**Issue by zentuit** [soomla/ios-store#43]
A few days ago, while testing I had a situation occur that I've had happen before but this time I took the time to track it down. What happened was a non-200 response code was returned from the Soomla verification server (or possibly the verification failed??) on a purchase of a consumable market item. What I saw in the device logs was output from 
```
LogError(TAG, ([NSString stringWithFormat:@"There was a problem when verifying (%@). Will try again later.", errorMsg]));
[StoreEventHandling postVerificationError:errorCode forObject:self];      
```
That had cascading implications. First, the `postVerificationError` event, `[[SKPaymentQueue defaultQueue] finishTransaction: transaction];` would never get fired. This left a completed transaction in the SKPaymentQueue, so then on every relaunch of my game, I would get the password popup.

Now, this is the interesting part. There isn't any code to handle clearing out completed (consumable) transactions. I'm assuming that a call to `[[SKPaymentQueue defaultQueue] restoreCompletedTransactions];` would clear out any non-consumable item purchases, but it won't fire `paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions` on any consumables.  Effectively, the customer (in this case my test user) would be charged for the purchase but would never be able to receive the item.

I did some research and it turns out that for this situation we just have to resubmit these completed transactions to the verification server.

I've added a new method to *SoomlaStore.m* that *UnitySoomlaStore.mm* calls that will loop over `[[SKPaymentQueue defaultQueue] transactions];` and if the `transaction` is in the *SKPaymentTransactionStatePurchased* state, will call `[self givePurchasedItem:transaction];`. This effectively restarts the verification procedure.

To start the whole thing automatically, I updated *SoomlaStore.cs Initialize* method to call the method to retry unfinished transactions after `instance._refreshMarketItemsDetails();` (in the UNITY_IOS block).

I have that working beautifully.

Next I felt that verification was shorted in the Events area. So I added some new events: 
* EVENT_VERIFICATION_STARTED via `postVerificationStarted`
* EVENT_VERIFICATION_ERROR via `postVerificationError`
* EVENT_VERIFICATION_FAILED

*EVENT_VERIFICATION_STARTED* lets us know that the processing has moved from the App Store to the verification server.

*EVENT_VERIFICATION_ERROR* lets us know that there was an issue trying to verify the receipt. I've replaced all of the *EVENT_UNEXPECTED_ERROR_IN_STORE* events in *SoomlaVerification.m* with *EVENT_VERIFICATION_ERROR* events. This makes sense to me because by the time we get to *SoomlaVerification.m*, the purchase has been completed in the App Store so they are really verification server issues.  

*EVENT_VERIFICATION_FAILED* lets us know that the verification process completed successfully but the verification itself failed. That entailed changing the *EVENT_UNEXPECTED_ERROR_IN_STORE* event to *EVENT_VERIFICATION_FAILED* in *purchaseVerified* method.

**Note that this last two changes are breaking changes for people relying on onUnexpectedErrorInStore events when verifying.** 

The only way around that is to keep the store error event but also call the verification events after the unexpected store error event. That way the developer can set a flag in the verification started event handler and ignore the store error event handling if that flag is set. Kind of clunky but not terrible.

I have all of this working nicely and should be pushing it up to my fork today. I wanted to give you the heads up.

Also I think I could write up a couple of paragraphs on the new events for including in the Events section of the Knowledge base.

**Comment by refaelos** [comment]
You raise some interesting points that we decided to handle a curtain way and might be changed if there's a good reason to change.

Can you post this to http://answers.soom.la ?
(I'll answer there)

**Comment by refaelos** [comment]
We're talking about this on the forum... closing.
