### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by robertodias180** [soomla/ios-store#71]
I am getting a memory leak in [SKPaymentQueue canMakePayments]. 

Leaked Object	#	Address	Size	Responsible Library	Responsible Frame
OS_dispatch_semaphore	1	0x17409dc40	80 Bytes	StoreKit	+[SKPaymentQueue canMakePayments]

Is this a bug in soomla or an iOS bug?

**Comment by iosphile** [comment]
Hi Robert,
I am having same memory leak.Have you solved the issue?

**Comment by JesseNoBata** [comment]
Same issue here. Bump
